name: 'OQOQO Bot - PR Analysis & Documentation'
description: 'Intelligent PR analysis with Hot-Path semantic analysis and AI-powered documentation generation'
author: 'OQOQO Bot Team'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  mode:
    description: 'Operation mode: "analyze" for PR analysis or "update-docs" for documentation generation'
    required: false
    default: 'analyze'

  enable-llm:
    description: 'Enable LLM features for AI-powered suggestions (true/false)'
    required: false
    default: 'true'

  openai-api-key:
    description: 'OpenAI API key (required if enable-llm is true)'
    required: false

  anthropic-api-key:
    description: 'Anthropic API key (alternative to OpenAI)'
    required: false

  docs-dir:
    description: 'Documentation directory'
    required: false
    default: 'docs'

  docs-extras:
    description: 'Additional documentation files (comma-separated)'
    required: false
    default: 'README.md'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install requests openai anthropic

    - name: Fetch PR details (if needed)
      shell: bash
      if: github.event_name == 'issue_comment' || github.event.pull_request.base.sha == ''
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
      run: |
        # Fetch PR details using GitHub API (Python is already installed)
        python3 << 'EOF'
        import os
        import json
        import urllib.request
        
        token = os.environ['GITHUB_TOKEN']
        repo = os.environ['REPO']
        pr_number = os.environ['PR_NUMBER']
        
        url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}"
        req = urllib.request.Request(url)
        req.add_header("Authorization", f"Bearer {token}")
        req.add_header("Accept", "application/vnd.github+json")
        
        with urllib.request.urlopen(req) as response:
            pr_data = json.loads(response.read())
        
        base_sha = pr_data['base']['sha']
        head_sha = pr_data['head']['sha']
        
        # Write to GITHUB_ENV for next step
        with open(os.environ['GITHUB_ENV'], 'a') as f:
            f.write(f"BASE_SHA={base_sha}\n")
            f.write(f"HEAD_SHA={head_sha}\n")
        
        print(f"Fetched PR details: base={base_sha[:8]}, head={head_sha[:8]}")
        EOF

    - name: Run OQOQO Bot
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
        BASE_SHA: ${{ github.event.pull_request.base.sha || env.BASE_SHA }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha || env.HEAD_SHA }}
        ENABLE_LLM: ${{ inputs.enable-llm }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        DOCS_DIR: ${{ inputs.docs-dir }}
        DOCS_EXTRAS: ${{ inputs.docs-extras }}
        REPO_PATH: ${{ github.workspace }}
      run: |
        export PYTHONPATH="${PYTHONPATH}:${{ github.action_path }}/src/hotpath"
        cd "${{ github.workspace }}"

        if [ "${{ inputs.mode }}" == "update-docs" ]; then
          python ${{ github.action_path }}/src/update_docs.py
        else
          python ${{ github.action_path }}/src/pr_bot.py
        fi
