name: OQOQO Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  analyze:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OQOQO Bot – PR Analysis & Documentation
        uses: haritha1313/oqoqo-bot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-llm: 'true'
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}

  update-docs:
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/update-docs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OQOQO Bot – Update Docs
        uses: haritha1313/oqoqo-bot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-llm: 'true'
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
